
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app/
    
hooks:
 
  Application Start:
    - location: scripts/appstart.sh
      timeout: 300
      runas: ubuntu
   
  Application Stop:
    - location: scripts/appstop.sh
      timeout: 300
      runas: ubuntu   

  

