version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app/
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 300
      runas: ubuntu   
