
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
    overwrite: true
    
hooks:
  Before Installation:
    - cd /home/ubuntu/node-express-realworld-example-app rm -rf *
  Application Start:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
     
  Application Stop:
    - location: scripts/appstop.sh
      timeout: 300
      runas: root
  

