version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 421320058418.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t node-docker .
      - docker tag mern-docker-a:latest 421320058418.dkr.ecr.ap-south-1.amazonaws.com/node-docker:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 421320058418.dkr.ecr.ap-south-1.amazonaws.com/node-docker:latest
      - printf '[{"name":"node-docker","imageUri":"%s"}]' 421320058418.dkr.ecr.ap-south-1.amazonaws.com/node-docker:latest > imagedefinitions.json

artifacts:
  files:
     - imagedefinitions.json
  
