version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
    
