version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
  build:
    commands:
      - cd /home/ubuntu/node-express-realworld-example-app
      - sed -i 's/localhost/65.1.132.122:27017/' app.js
      - echo Build started on `date`
      - echo Compiling
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
    
